questions:
  "TED's new partnership":
    - TED@NRA
    - TED@CambridgeAnalytica
    - TED@Monsanto
    - TED@Ticketmaster
  "Small Thing Big Idea: Season 2 episode":
    - Single use plastic bags
    - '"Subscribe to our newsletter" popups'
    - Fake news
  "TED's next audacious initiative":
    - Flirtatious project
    - Superstitious project
    - Fallacious project
