"New TED shapes":
    - Squares
    - Triangles
    - Rhombii


  "Initiatives for the next year":
    - Meat Week
    - Patriarchy
    - Company-wide sabbatical
    - Just, like, look at the sky, man.
    - Hey, what's goin' on?



    - WorkLife with Adam Smith
    - JediLife with Adam Driver
    - HomeLife with Adam and Eve



    - TEDxNightVale
    - My Dad Wrote a Highly Inappropriate TED Talk

    - -------- with Adam Sandler

    - The TED Interview


    - Norman doors
    - Ball pits
