questions:
  "What is your favorite color?":
    - Blue
    - Green
    - Red
    - Paisley
  "How great is bacon?":
    - Yum
    - Yuck
  "The next Audacious project is...":
    - Fallacious project
    - Ostentatious project
    - Cretatious project
    - Delicious project
    - Superstious project
